### ISSUE TITLE
[BUG] ML does not work

### ISSUE THREAD

**Issue by ChangwooLim** [statgarten/door#68]
**Describe the bug**

**To Reproduce**
1. Go to Datatoys->accident->Import Data->ML->Data Setup(저는 부상자수로 했습니다)->Modeling->Build Model
2. Click on '
3. Scroll down to 
Warning: Error in stove::logisticRegression: unused arguments (gridNum = input$gridNum, iter = input$iter, seed = input$seed)
  3: runApp
  2: print.shiny.appobj
  1: <Anonymous>

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jhk0530** [comment]
ML module requires precise data. 
`accident` needs to change before running ML.
1. remove `발생년` since it's only consisted with one value. (is not usefull as Linear regression variable)
2. remove `발생년월일시` since regression not use datetime
3. change **character** values to **factor**

after this preprocess, data will looks like below image.

![스크린샷 2023-10-11 오전 11 10 53](https://github.com/statgarten/door/assets/6457691/4967eadc-079f-4b4c-a545-17bdf9b88a06)

and it will work.

![스크린샷 2023-10-11 오전 11 11 49](https://github.com/statgarten/door/assets/6457691/c82a2e8a-f263-45ae-99ea-a4d10f7059e3)
